# Generated by Django 3.2.25 on 2024-07-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
    ]
