# Generated by Django 3.2.25 on 2024-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
